# This is a basic workflow to help you get started with Actions
name: CF-Run-Hana-Cloud

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called run-hana-clou
  run-hana-cloud:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Run command with CF-CLI Cloud Foundry
        uses: guerric-p/cf-cli-action@master
        with:
          cf_api: https://api.cf.us10.hana.ondemand.com
          cf_username: ${{secrets.CF_USERNAME}}
          cf_password: ${{secrets.CF_PASSWORD}}
          cf_org: 3ff7e55dtrial
          cf_space: dev
          command: apps | grep started | awk {'print $1}{system ("cf update-service mySAPHanaInstance -c '{"action":"RUNNING"}'" $1)}'
